#!/usr/bin/env bash
set -euo pipefail
: "${OPENCV_SOURCE_DIR:?Set OPENCV_SOURCE_DIR to the OpenCV source directory}"
: "${OPENCV_BUILD_DIR:?Set OPENCV_BUILD_DIR to the OpenCV build directory}"
cmake -S "$OPENCV_SOURCE_DIR" -B "$OPENCV_BUILD_DIR" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_LIST=core,imgproc,imgcodecs,dnn,ts \
  -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DBUILD_PERF_TESTS=ON \
  -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF \
  -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_java=OFF \
  -DWITH_IPP=OFF -DWITH_OPENCL=OFF -DWITH_TBB=OFF \
  -DWITH_LAPACK=OFF -DWITH_EIGEN=OFF \
  -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_GTK=OFF -DWITH_QT=OFF \
  -DWITH_AVIF=OFF -DWITH_OPENEXR=OFF -DWITH_TIFF=OFF -DWITH_WEBP=OFF \
  -DWITH_JASPER=OFF -DWITH_JPEGXL=OFF -DWITH_HARFBUZZ=OFF \
  -DWITH_OPENJPEG=OFF -DWITH_OBSENSOR=OFF -DBUILD_DOCS=OFF \
  -DCPU_BASELINE=SSE3 -DCPU_DISPATCH=AVX2 \
  -DENABLE_PRECOMPILED_HEADERS=OFF -DOPENCV_ENABLE_NONFREE=OFF
